// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

package reportpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Report struct {
	CreatedAt            string   `protobuf:"bytes,1,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	AcquirerID           string   `protobuf:"bytes,2,opt,name=AcquirerID,proto3" json:"AcquirerID,omitempty"`
	MerchantID           string   `protobuf:"bytes,3,opt,name=MerchantID,proto3" json:"MerchantID,omitempty"`
	PaymentID            string   `protobuf:"bytes,4,opt,name=PaymentID,proto3" json:"PaymentID,omitempty"`
	ReportID             string   `protobuf:"bytes,5,opt,name=ReportID,proto3" json:"ReportID,omitempty"`
	ReportType           string   `protobuf:"bytes,6,opt,name=ReportType,proto3" json:"ReportType,omitempty"`
	FileType             string   `protobuf:"bytes,7,opt,name=FileType,proto3" json:"FileType,omitempty"`
	FileName             string   `protobuf:"bytes,8,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FilePath             string   `protobuf:"bytes,9,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{0}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Report) GetAcquirerID() string {
	if m != nil {
		return m.AcquirerID
	}
	return ""
}

func (m *Report) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *Report) GetPaymentID() string {
	if m != nil {
		return m.PaymentID
	}
	return ""
}

func (m *Report) GetReportID() string {
	if m != nil {
		return m.ReportID
	}
	return ""
}

func (m *Report) GetReportType() string {
	if m != nil {
		return m.ReportType
	}
	return ""
}

func (m *Report) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *Report) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Report) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type GenerateReportReq struct {
	Report               *Report  `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateReportReq) Reset()         { *m = GenerateReportReq{} }
func (m *GenerateReportReq) String() string { return proto.CompactTextString(m) }
func (*GenerateReportReq) ProtoMessage()    {}
func (*GenerateReportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{1}
}

func (m *GenerateReportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateReportReq.Unmarshal(m, b)
}
func (m *GenerateReportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateReportReq.Marshal(b, m, deterministic)
}
func (m *GenerateReportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateReportReq.Merge(m, src)
}
func (m *GenerateReportReq) XXX_Size() int {
	return xxx_messageInfo_GenerateReportReq.Size(m)
}
func (m *GenerateReportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateReportReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateReportReq proto.InternalMessageInfo

func (m *GenerateReportReq) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

type GenerateReportRes struct {
	Report               *Report  `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateReportRes) Reset()         { *m = GenerateReportRes{} }
func (m *GenerateReportRes) String() string { return proto.CompactTextString(m) }
func (*GenerateReportRes) ProtoMessage()    {}
func (*GenerateReportRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{2}
}

func (m *GenerateReportRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateReportRes.Unmarshal(m, b)
}
func (m *GenerateReportRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateReportRes.Marshal(b, m, deterministic)
}
func (m *GenerateReportRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateReportRes.Merge(m, src)
}
func (m *GenerateReportRes) XXX_Size() int {
	return xxx_messageInfo_GenerateReportRes.Size(m)
}
func (m *GenerateReportRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateReportRes.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateReportRes proto.InternalMessageInfo

func (m *GenerateReportRes) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func init() {
	proto.RegisterType((*Report)(nil), "report.Report")
	proto.RegisterType((*GenerateReportReq)(nil), "report.GenerateReportReq")
	proto.RegisterType((*GenerateReportRes)(nil), "report.GenerateReportRes")
}

func init() {
	proto.RegisterFile("report.proto", fileDescriptor_3eedb623aa6ca98c)
}

var fileDescriptor_3eedb623aa6ca98c = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0xd9, 0xd4, 0xd8, 0x7e, 0xea, 0xc0, 0x9c, 0xe2, 0x10, 0x91, 0x1d, 0xc4, 0xd3, 0x0e,
	0xf3, 0xe8, 0x69, 0x5a, 0x26, 0x3d, 0x28, 0xa3, 0x0a, 0x82, 0xb7, 0xac, 0x7e, 0xb0, 0x82, 0x5b,
	0xb3, 0x6f, 0x51, 0xd8, 0xff, 0xe1, 0x1f, 0x2c, 0xc9, 0xd7, 0x34, 0x8a, 0x0a, 0xbb, 0xe5, 0xbd,
	0x5f, 0xdf, 0x6b, 0x78, 0x04, 0x0e, 0x09, 0x4d, 0x4d, 0x76, 0x68, 0xa8, 0xb6, 0xb5, 0x14, 0xac,
	0x06, 0x9f, 0x5d, 0x10, 0x85, 0x3f, 0xca, 0x53, 0x48, 0x6f, 0x09, 0xb5, 0xc5, 0xd7, 0xb1, 0x55,
	0x9d, 0xf3, 0xce, 0x65, 0x5a, 0x44, 0x43, 0x9e, 0x01, 0x8c, 0xcb, 0xd5, 0x7b, 0x45, 0x48, 0x79,
	0xa6, 0xba, 0x1e, 0x7f, 0x73, 0x1c, 0xbf, 0x47, 0x2a, 0xe7, 0x7a, 0x69, 0xf3, 0x4c, 0xed, 0x30,
	0x8f, 0x8e, 0x6b, 0x9f, 0xea, 0xcd, 0x02, 0x3d, 0xde, 0xe5, 0xf6, 0xd6, 0x90, 0x7d, 0x48, 0xf8,
	0x16, 0x79, 0xa6, 0xf6, 0x3c, 0x6c, 0xb5, 0x6b, 0xe6, 0xf3, 0xd3, 0xc6, 0xa0, 0x12, 0xdc, 0x1c,
	0x1d, 0x97, 0x9d, 0x54, 0x6f, 0xe8, 0xe9, 0x3e, 0x67, 0x83, 0x0e, 0xec, 0x41, 0x2f, 0x50, 0x25,
	0x91, 0x39, 0x1d, 0xd8, 0x54, 0xdb, 0xb9, 0x4a, 0x23, 0x73, 0x7a, 0x70, 0x0d, 0xc7, 0x77, 0xb8,
	0x44, 0xd2, 0x16, 0xf9, 0x4f, 0x05, 0xae, 0xe4, 0x05, 0x34, 0xab, 0xf9, 0x75, 0x0e, 0x46, 0xbd,
	0x61, 0x33, 0x69, 0xf3, 0x49, 0xd8, 0xf4, 0x8f, 0xf0, 0x7a, 0xdb, 0xf0, 0xe8, 0x19, 0x8e, 0xd8,
	0x79, 0x44, 0xfa, 0xa8, 0x4a, 0x94, 0x13, 0xe8, 0xfd, 0x6c, 0x93, 0x27, 0x21, 0xfa, 0xeb, 0x8a,
	0xfd, 0x7f, 0xd1, 0xfa, 0x06, 0x5e, 0x12, 0x66, 0x66, 0x36, 0x13, 0xfe, 0x11, 0x5c, 0x7d, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x30, 0x21, 0x85, 0xf5, 0x14, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportServiceClient interface {
	GenerateReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*GenerateReportRes, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) GenerateReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*GenerateReportRes, error) {
	out := new(GenerateReportRes)
	err := c.cc.Invoke(ctx, "/report.ReportService/GenerateReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
type ReportServiceServer interface {
	GenerateReport(context.Context, *GenerateReportReq) (*GenerateReportRes, error)
}

// UnimplementedReportServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReportServiceServer struct {
}

func (*UnimplementedReportServiceServer) GenerateReport(ctx context.Context, req *GenerateReportReq) (*GenerateReportRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateReport not implemented")
}

func RegisterReportServiceServer(s *grpc.Server, srv ReportServiceServer) {
	s.RegisterService(&_ReportService_serviceDesc, srv)
}

func _ReportService_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.ReportService/GenerateReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).GenerateReport(ctx, req.(*GenerateReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReportService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "report.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateReport",
			Handler:    _ReportService_GenerateReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}
