// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package paymentpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payment struct {
	AcquirerId           string   `protobuf:"bytes,1,opt,name=AcquirerId,proto3" json:"AcquirerId,omitempty"`
	StartDate            string   `protobuf:"bytes,2,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate              string   `protobuf:"bytes,3,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetAcquirerId() string {
	if m != nil {
		return m.AcquirerId
	}
	return ""
}

func (m *Payment) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Payment) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type RunPaymentReq struct {
	Payment              *Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunPaymentReq) Reset()         { *m = RunPaymentReq{} }
func (m *RunPaymentReq) String() string { return proto.CompactTextString(m) }
func (*RunPaymentReq) ProtoMessage()    {}
func (*RunPaymentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *RunPaymentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPaymentReq.Unmarshal(m, b)
}
func (m *RunPaymentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPaymentReq.Marshal(b, m, deterministic)
}
func (m *RunPaymentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPaymentReq.Merge(m, src)
}
func (m *RunPaymentReq) XXX_Size() int {
	return xxx_messageInfo_RunPaymentReq.Size(m)
}
func (m *RunPaymentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPaymentReq.DiscardUnknown(m)
}

var xxx_messageInfo_RunPaymentReq proto.InternalMessageInfo

func (m *RunPaymentReq) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

type RunPaymentRes struct {
	Payment              *Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunPaymentRes) Reset()         { *m = RunPaymentRes{} }
func (m *RunPaymentRes) String() string { return proto.CompactTextString(m) }
func (*RunPaymentRes) ProtoMessage()    {}
func (*RunPaymentRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *RunPaymentRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPaymentRes.Unmarshal(m, b)
}
func (m *RunPaymentRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPaymentRes.Marshal(b, m, deterministic)
}
func (m *RunPaymentRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPaymentRes.Merge(m, src)
}
func (m *RunPaymentRes) XXX_Size() int {
	return xxx_messageInfo_RunPaymentRes.Size(m)
}
func (m *RunPaymentRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPaymentRes.DiscardUnknown(m)
}

var xxx_messageInfo_RunPaymentRes proto.InternalMessageInfo

func (m *RunPaymentRes) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func init() {
	proto.RegisterType((*Payment)(nil), "payment.Payment")
	proto.RegisterType((*RunPaymentReq)(nil), "payment.RunPaymentReq")
	proto.RegisterType((*RunPaymentRes)(nil), "payment.RunPaymentRes")
}

func init() {
	proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410)
}

var fileDescriptor_6362648dfa63d410 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xac, 0xcc,
	0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x12, 0xb9,
	0xd8, 0x03, 0x20, 0x4c, 0x21, 0x39, 0x2e, 0x2e, 0xc7, 0xe4, 0xc2, 0xd2, 0xcc, 0xa2, 0xd4, 0x22,
	0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x24, 0x11, 0x21, 0x19, 0x2e, 0xce, 0xe0,
	0x92, 0xc4, 0xa2, 0x12, 0x97, 0xc4, 0x92, 0x54, 0x09, 0x26, 0xb0, 0x34, 0x42, 0x40, 0x48, 0x82,
	0x8b, 0xdd, 0x35, 0x2f, 0x05, 0x2c, 0xc7, 0x0c, 0x96, 0x83, 0x71, 0x95, 0xac, 0xb9, 0x78, 0x83,
	0x4a, 0xf3, 0xa0, 0xb6, 0x04, 0xa5, 0x16, 0x0a, 0x69, 0x71, 0xc1, 0xac, 0x07, 0xdb, 0xc2, 0x6d,
	0x24, 0xa0, 0x07, 0x73, 0x1d, 0x4c, 0x15, 0xdc, 0x7d, 0x68, 0x9a, 0x8b, 0x49, 0xd1, 0x6c, 0xe4,
	0xc7, 0xc5, 0x07, 0x15, 0x0b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xb2, 0xe1, 0xe2, 0x42,
	0x18, 0x27, 0x24, 0x06, 0xd7, 0x8a, 0xe2, 0x40, 0x29, 0xec, 0xe2, 0xc5, 0x4e, 0xdc, 0x51, 0x9c,
	0x50, 0x89, 0x82, 0xa4, 0x24, 0x36, 0x70, 0x48, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x67,
	0xaf, 0xeb, 0x42, 0x5a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	RunPayment(ctx context.Context, in *RunPaymentReq, opts ...grpc.CallOption) (*RunPaymentRes, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) RunPayment(ctx context.Context, in *RunPaymentReq, opts ...grpc.CallOption) (*RunPaymentRes, error) {
	out := new(RunPaymentRes)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/RunPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	RunPayment(context.Context, *RunPaymentReq) (*RunPaymentRes, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) RunPayment(ctx context.Context, req *RunPaymentReq) (*RunPaymentRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunPayment not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_RunPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RunPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/RunPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RunPayment(ctx, req.(*RunPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunPayment",
			Handler:    _PaymentService_RunPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
